# Generated by Django 5.0.3 on 2024-04-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_devolução',
            new_name='data_devolucao',
        ),
    ]
